/**
 * Medical Synonym Dictionary for Semantic Search
 *
 * Maps common medical/scientific terms, abbreviations, organ names, disease names,
 * procedure types, and research terminology to the 47 subject areas used in the
 * journal database. This enables semantic search — e.g. searching "heart" will
 * match journals tagged with "Cardiology".
 */

// Each key is a lowercase search term; values are the subject areas it maps to.
export const MEDICAL_SYNONYMS: Record<string, string[]> = {
  // ============================================================================
  // ORGAN SYSTEMS & ANATOMY
  // ============================================================================

  // Cardiovascular
  heart: ["Cardiology"],
  cardiac: ["Cardiology"],
  coronary: ["Cardiology"],
  cardiovascular: ["Cardiology"],
  myocardial: ["Cardiology"],
  atrial: ["Cardiology"],
  ventricular: ["Cardiology"],
  aortic: ["Cardiology"],
  valve: ["Cardiology"],
  arrhythmia: ["Cardiology"],
  pacemaker: ["Cardiology"],
  echocardiography: ["Cardiology"],
  angioplasty: ["Cardiology"],
  stent: ["Cardiology"],
  atherosclerosis: ["Cardiology"],
  hypertension: ["Cardiology"],
  hypotension: ["Cardiology"],
  "blood pressure": ["Cardiology"],
  "heart failure": ["Cardiology"],
  "heart attack": ["Cardiology"],
  infarction: ["Cardiology"],
  ischemia: ["Cardiology"],
  ischemic: ["Cardiology"],
  "congenital heart": ["Cardiology", "Pediatrics"],
  endocarditis: ["Cardiology", "Infectious Disease"],
  pericarditis: ["Cardiology"],
  cardiomyopathy: ["Cardiology"],
  tachycardia: ["Cardiology"],
  bradycardia: ["Cardiology"],
  "atrial fibrillation": ["Cardiology"],
  angina: ["Cardiology"],

  // Neurology / Neuroscience
  brain: ["Neurology", "Neuroscience"],
  cerebral: ["Neurology", "Neuroscience"],
  cortex: ["Neurology", "Neuroscience"],
  cortical: ["Neurology", "Neuroscience"],
  neural: ["Neurology", "Neuroscience"],
  neuron: ["Neurology", "Neuroscience"],
  neuronal: ["Neurology", "Neuroscience"],
  synapse: ["Neuroscience"],
  synaptic: ["Neuroscience"],
  neurotransmitter: ["Neuroscience"],
  dopamine: ["Neuroscience", "Psychiatry"],
  serotonin: ["Neuroscience", "Psychiatry"],
  "spinal cord": ["Neurology"],
  spinal: ["Neurology", "Orthopedics"],
  meningitis: ["Neurology", "Infectious Disease"],
  encephalitis: ["Neurology", "Infectious Disease"],
  neuropathy: ["Neurology"],
  "multiple sclerosis": ["Neurology", "Immunology"],
  myelitis: ["Neurology"],
  "blood-brain barrier": ["Neuroscience"],
  hippocampus: ["Neuroscience"],
  amygdala: ["Neuroscience"],
  cerebellum: ["Neurology", "Neuroscience"],
  neuroimaging: ["Neurology", "Radiology"],
  EEG: ["Neurology"],
  electroencephalography: ["Neurology"],
  "nerve": ["Neurology"],
  cranial: ["Neurology"],
  cognitive: ["Neuroscience", "Psychology"],
  cognition: ["Neuroscience", "Psychology"],

  // Pulmonology / Respiratory
  lung: ["Pulmonology"],
  lungs: ["Pulmonology"],
  pulmonary: ["Pulmonology"],
  respiratory: ["Pulmonology"],
  bronchial: ["Pulmonology"],
  bronchus: ["Pulmonology"],
  alveolar: ["Pulmonology"],
  pleural: ["Pulmonology"],
  thoracic: ["Pulmonology", "Surgery"],
  asthma: ["Pulmonology", "Immunology"],
  COPD: ["Pulmonology"],
  pneumonia: ["Pulmonology", "Infectious Disease"],
  tuberculosis: ["Pulmonology", "Infectious Disease"],
  "pulmonary fibrosis": ["Pulmonology"],
  emphysema: ["Pulmonology"],
  bronchitis: ["Pulmonology"],
  "cystic fibrosis": ["Pulmonology", "Genetics"],
  ventilator: ["Pulmonology", "Critical Care"],
  spirometry: ["Pulmonology"],
  "sleep apnea": ["Pulmonology"],
  dyspnea: ["Pulmonology"],

  // Gastroenterology
  liver: ["Gastroenterology"],
  hepatic: ["Gastroenterology"],
  hepatitis: ["Gastroenterology", "Infectious Disease"],
  cirrhosis: ["Gastroenterology"],
  stomach: ["Gastroenterology"],
  gastric: ["Gastroenterology"],
  intestine: ["Gastroenterology"],
  intestinal: ["Gastroenterology"],
  colon: ["Gastroenterology"],
  colonic: ["Gastroenterology"],
  colorectal: ["Gastroenterology", "Oncology"],
  rectal: ["Gastroenterology"],
  pancreas: ["Gastroenterology"],
  pancreatic: ["Gastroenterology"],
  gallbladder: ["Gastroenterology"],
  biliary: ["Gastroenterology"],
  esophageal: ["Gastroenterology"],
  esophagus: ["Gastroenterology"],
  GI: ["Gastroenterology"],
  gastrointestinal: ["Gastroenterology"],
  "inflammatory bowel": ["Gastroenterology", "Immunology"],
  crohn: ["Gastroenterology", "Immunology"],
  "ulcerative colitis": ["Gastroenterology", "Immunology"],
  celiac: ["Gastroenterology", "Immunology"],
  "irritable bowel": ["Gastroenterology"],
  endoscopy: ["Gastroenterology"],
  colonoscopy: ["Gastroenterology"],
  GERD: ["Gastroenterology"],
  dyspepsia: ["Gastroenterology"],
  jaundice: ["Gastroenterology"],

  // Nephrology
  kidney: ["Nephrology"],
  kidneys: ["Nephrology"],
  renal: ["Nephrology"],
  nephron: ["Nephrology"],
  dialysis: ["Nephrology"],
  glomerular: ["Nephrology"],
  glomerulonephritis: ["Nephrology"],
  "kidney failure": ["Nephrology"],
  "chronic kidney": ["Nephrology"],
  "acute kidney": ["Nephrology"],
  proteinuria: ["Nephrology"],
  creatinine: ["Nephrology"],
  "renal transplant": ["Nephrology", "Surgery"],
  nephrotic: ["Nephrology"],

  // Dermatology
  skin: ["Dermatology"],
  cutaneous: ["Dermatology"],
  epidermal: ["Dermatology"],
  epidermis: ["Dermatology"],
  dermis: ["Dermatology"],
  dermal: ["Dermatology"],
  eczema: ["Dermatology", "Immunology"],
  psoriasis: ["Dermatology", "Immunology"],
  melanoma: ["Dermatology", "Oncology"],
  acne: ["Dermatology"],
  rash: ["Dermatology"],
  urticaria: ["Dermatology", "Immunology"],
  wound: ["Dermatology", "Surgery"],
  "wound healing": ["Dermatology", "Regenerative Medicine"],
  alopecia: ["Dermatology"],
  vitiligo: ["Dermatology"],
  dermatitis: ["Dermatology"],
  keratinocyte: ["Dermatology", "Cell Biology"],

  // Ophthalmology
  eye: ["Ophthalmology"],
  eyes: ["Ophthalmology"],
  ocular: ["Ophthalmology"],
  retina: ["Ophthalmology"],
  retinal: ["Ophthalmology"],
  cornea: ["Ophthalmology"],
  corneal: ["Ophthalmology"],
  glaucoma: ["Ophthalmology"],
  cataract: ["Ophthalmology"],
  "macular degeneration": ["Ophthalmology"],
  optic: ["Ophthalmology"],
  visual: ["Ophthalmology", "Neuroscience"],
  vision: ["Ophthalmology"],
  intraocular: ["Ophthalmology"],
  conjunctivitis: ["Ophthalmology"],
  uveitis: ["Ophthalmology"],
  "diabetic retinopathy": ["Ophthalmology", "Endocrinology"],
  keratitis: ["Ophthalmology"],
  lens: ["Ophthalmology"],

  // Otolaryngology (ENT)
  ear: ["Otolaryngology"],
  hearing: ["Otolaryngology"],
  auditory: ["Otolaryngology"],
  cochlear: ["Otolaryngology"],
  vestibular: ["Otolaryngology"],
  tinnitus: ["Otolaryngology"],
  nose: ["Otolaryngology"],
  nasal: ["Otolaryngology"],
  sinus: ["Otolaryngology"],
  sinusitis: ["Otolaryngology"],
  throat: ["Otolaryngology"],
  larynx: ["Otolaryngology"],
  laryngeal: ["Otolaryngology"],
  pharynx: ["Otolaryngology"],
  pharyngeal: ["Otolaryngology"],
  tonsil: ["Otolaryngology"],
  ENT: ["Otolaryngology"],
  deafness: ["Otolaryngology"],
  vertigo: ["Otolaryngology"],
  "hearing loss": ["Otolaryngology"],
  "cochlear implant": ["Otolaryngology", "Biomedical Engineering"],

  // Orthopedics / Musculoskeletal
  bone: ["Orthopedics"],
  bones: ["Orthopedics"],
  joint: ["Orthopedics"],
  joints: ["Orthopedics"],
  fracture: ["Orthopedics"],
  musculoskeletal: ["Orthopedics"],
  orthopedic: ["Orthopedics"],
  orthopaedic: ["Orthopedics"],
  cartilage: ["Orthopedics"],
  tendon: ["Orthopedics"],
  ligament: ["Orthopedics"],
  meniscus: ["Orthopedics"],
  spine: ["Orthopedics"],
  vertebral: ["Orthopedics"],
  scoliosis: ["Orthopedics"],
  osteoporosis: ["Orthopedics", "Endocrinology"],
  osteoarthritis: ["Orthopedics", "Rheumatology"],
  arthroplasty: ["Orthopedics", "Surgery"],
  ACL: ["Orthopedics", "Sports Medicine"],
  hip: ["Orthopedics"],
  knee: ["Orthopedics"],
  shoulder: ["Orthopedics"],
  "rotator cuff": ["Orthopedics"],
  osteosarcoma: ["Orthopedics", "Oncology"],

  // Hematology / Blood
  blood: ["Hematology"],
  hematologic: ["Hematology"],
  hematopoietic: ["Hematology"],
  hemoglobin: ["Hematology"],
  platelet: ["Hematology"],
  coagulation: ["Hematology"],
  thrombosis: ["Hematology"],
  embolism: ["Hematology"],
  "deep vein thrombosis": ["Hematology"],
  DVT: ["Hematology"],
  anemia: ["Hematology"],
  sickle: ["Hematology", "Genetics"],
  "sickle cell": ["Hematology", "Genetics"],
  hemophilia: ["Hematology", "Genetics"],
  anticoagulant: ["Hematology"],
  transfusion: ["Hematology"],
  "bone marrow": ["Hematology", "Oncology"],
  lymphoma: ["Hematology", "Oncology"],
  leukemia: ["Hematology", "Oncology"],
  myeloma: ["Hematology", "Oncology"],
  hemorrhage: ["Hematology"],
  bleeding: ["Hematology"],

  // Urology
  prostate: ["Urology"],
  prostatic: ["Urology"],
  bladder: ["Urology"],
  urinary: ["Urology"],
  urologic: ["Urology"],
  urethra: ["Urology"],
  ureter: ["Urology"],
  "urinary tract": ["Urology", "Infectious Disease"],
  UTI: ["Urology", "Infectious Disease"],
  incontinence: ["Urology"],
  "erectile dysfunction": ["Urology"],
  cystitis: ["Urology"],
  nephrolithiasis: ["Urology", "Nephrology"],
  "kidney stone": ["Urology", "Nephrology"],

  // Obstetrics / Gynecology / Reproductive
  uterus: ["Obstetrics", "Gynecology"],
  uterine: ["Obstetrics", "Gynecology"],
  ovary: ["Gynecology", "Reproductive Medicine"],
  ovarian: ["Gynecology", "Reproductive Medicine"],
  cervical: ["Gynecology"],
  cervix: ["Gynecology"],
  endometrial: ["Gynecology"],
  endometriosis: ["Gynecology"],
  fertility: ["Reproductive Medicine"],
  infertility: ["Reproductive Medicine"],
  IVF: ["Reproductive Medicine"],
  "in vitro fertilization": ["Reproductive Medicine"],
  contraception: ["Gynecology", "Reproductive Medicine"],
  menstrual: ["Gynecology"],
  menopause: ["Gynecology", "Endocrinology"],
  pregnancy: ["Obstetrics"],
  pregnant: ["Obstetrics"],
  prenatal: ["Obstetrics"],
  postnatal: ["Obstetrics", "Pediatrics"],
  maternal: ["Obstetrics"],
  fetal: ["Obstetrics"],
  fetus: ["Obstetrics"],
  placenta: ["Obstetrics"],
  preeclampsia: ["Obstetrics"],
  eclampsia: ["Obstetrics"],
  cesarean: ["Obstetrics", "Surgery"],
  "c-section": ["Obstetrics", "Surgery"],
  labor: ["Obstetrics"],
  delivery: ["Obstetrics"],
  miscarriage: ["Obstetrics"],
  gestational: ["Obstetrics"],
  neonatal: ["Pediatrics", "Obstetrics"],
  neonate: ["Pediatrics", "Obstetrics"],
  embryo: ["Reproductive Medicine"],
  embryonic: ["Reproductive Medicine", "Cell Biology"],
  sperm: ["Reproductive Medicine"],
  "polycystic ovary": ["Gynecology", "Endocrinology"],
  PCOS: ["Gynecology", "Endocrinology"],

  // ============================================================================
  // DISEASES & CONDITIONS
  // ============================================================================

  // Oncology / Cancer
  cancer: ["Oncology"],
  tumor: ["Oncology"],
  tumour: ["Oncology"],
  malignant: ["Oncology"],
  malignancy: ["Oncology"],
  carcinoma: ["Oncology"],
  sarcoma: ["Oncology"],
  neoplasm: ["Oncology"],
  neoplastic: ["Oncology"],
  metastasis: ["Oncology"],
  metastatic: ["Oncology"],
  oncology: ["Oncology"],
  oncologic: ["Oncology"],
  chemotherapy: ["Oncology"],
  radiotherapy: ["Oncology", "Radiology"],
  immunotherapy: ["Oncology", "Immunology"],
  "breast cancer": ["Oncology"],
  "lung cancer": ["Oncology", "Pulmonology"],
  "prostate cancer": ["Oncology", "Urology"],
  glioblastoma: ["Oncology", "Neurology"],
  glioma: ["Oncology", "Neurology"],
  adenocarcinoma: ["Oncology"],
  "pancreatic cancer": ["Oncology", "Gastroenterology"],
  "ovarian cancer": ["Oncology", "Gynecology"],
  "cervical cancer": ["Oncology", "Gynecology"],
  "colon cancer": ["Oncology", "Gastroenterology"],
  hepatocellular: ["Oncology", "Gastroenterology"],
  biopsy: ["Oncology", "Pathology"],
  "tumor marker": ["Oncology"],
  staging: ["Oncology"],
  remission: ["Oncology"],
  "radiation therapy": ["Oncology", "Radiology"],

  // Endocrinology / Metabolic
  diabetes: ["Endocrinology"],
  diabetic: ["Endocrinology"],
  insulin: ["Endocrinology"],
  glycemic: ["Endocrinology"],
  glucose: ["Endocrinology"],
  "blood sugar": ["Endocrinology"],
  thyroid: ["Endocrinology"],
  hypothyroidism: ["Endocrinology"],
  hyperthyroidism: ["Endocrinology"],
  adrenal: ["Endocrinology"],
  pituitary: ["Endocrinology"],
  hormone: ["Endocrinology"],
  hormonal: ["Endocrinology"],
  endocrine: ["Endocrinology"],
  metabolic: ["Endocrinology"],
  metabolism: ["Endocrinology", "Biochemistry"],
  obesity: ["Endocrinology", "Public Health"],
  "type 1 diabetes": ["Endocrinology", "Immunology"],
  "type 2 diabetes": ["Endocrinology"],
  HbA1c: ["Endocrinology"],
  cortisol: ["Endocrinology"],
  testosterone: ["Endocrinology"],
  estrogen: ["Endocrinology"],
  "growth hormone": ["Endocrinology"],
  cushing: ["Endocrinology"],
  addison: ["Endocrinology"],

  // Neurology — diseases
  stroke: ["Neurology"],
  seizure: ["Neurology"],
  epilepsy: ["Neurology"],
  dementia: ["Neurology", "Psychiatry"],
  alzheimer: ["Neurology"],
  "alzheimer's": ["Neurology"],
  parkinson: ["Neurology"],
  "parkinson's": ["Neurology"],
  "huntington's": ["Neurology", "Genetics"],
  migraine: ["Neurology"],
  headache: ["Neurology"],
  "cerebrovascular": ["Neurology"],
  concussion: ["Neurology", "Sports Medicine"],
  "traumatic brain injury": ["Neurology", "Emergency Medicine"],
  TBI: ["Neurology", "Emergency Medicine"],
  ALS: ["Neurology"],
  "amyotrophic lateral sclerosis": ["Neurology"],
  "motor neuron": ["Neurology"],
  ataxia: ["Neurology"],
  dystonia: ["Neurology"],
  myasthenia: ["Neurology", "Immunology"],

  // Infectious Disease
  infection: ["Infectious Disease"],
  infectious: ["Infectious Disease"],
  HIV: ["Infectious Disease"],
  AIDS: ["Infectious Disease"],
  malaria: ["Infectious Disease"],
  TB: ["Infectious Disease"],
  sepsis: ["Infectious Disease", "Critical Care"],
  septic: ["Infectious Disease", "Critical Care"],
  antibiotic: ["Infectious Disease", "Pharmacology"],
  antimicrobial: ["Infectious Disease", "Microbiology"],
  antiviral: ["Infectious Disease", "Pharmacology"],
  antifungal: ["Infectious Disease", "Pharmacology"],
  influenza: ["Infectious Disease"],
  flu: ["Infectious Disease"],
  COVID: ["Infectious Disease", "Pulmonology"],
  "COVID-19": ["Infectious Disease", "Pulmonology"],
  coronavirus: ["Infectious Disease"],
  "SARS-CoV-2": ["Infectious Disease"],
  dengue: ["Infectious Disease"],
  zika: ["Infectious Disease"],
  ebola: ["Infectious Disease"],
  cholera: ["Infectious Disease"],
  typhoid: ["Infectious Disease"],
  meningococcal: ["Infectious Disease"],
  STI: ["Infectious Disease"],
  "sexually transmitted": ["Infectious Disease"],
  chlamydia: ["Infectious Disease"],
  gonorrhea: ["Infectious Disease"],
  syphilis: ["Infectious Disease"],
  "hepatitis B": ["Infectious Disease", "Gastroenterology"],
  "hepatitis C": ["Infectious Disease", "Gastroenterology"],
  pandemic: ["Infectious Disease", "Epidemiology", "Public Health"],
  epidemic: ["Infectious Disease", "Epidemiology"],
  pathogen: ["Infectious Disease", "Microbiology"],
  "drug resistance": ["Infectious Disease", "Microbiology"],
  MRSA: ["Infectious Disease", "Microbiology"],
  "antimicrobial resistance": ["Infectious Disease", "Microbiology"],

  // Psychiatry / Psychology
  depression: ["Psychiatry", "Psychology"],
  anxiety: ["Psychiatry", "Psychology"],
  schizophrenia: ["Psychiatry"],
  bipolar: ["Psychiatry"],
  "bipolar disorder": ["Psychiatry"],
  psychosis: ["Psychiatry"],
  psychotic: ["Psychiatry"],
  "mental health": ["Psychiatry", "Psychology"],
  "mental illness": ["Psychiatry"],
  psychiatric: ["Psychiatry"],
  psychological: ["Psychology"],
  PTSD: ["Psychiatry", "Psychology"],
  "post-traumatic stress": ["Psychiatry", "Psychology"],
  "eating disorder": ["Psychiatry", "Psychology"],
  anorexia: ["Psychiatry"],
  bulimia: ["Psychiatry"],
  OCD: ["Psychiatry"],
  "obsessive compulsive": ["Psychiatry"],
  ADHD: ["Psychiatry", "Pediatrics"],
  autism: ["Psychiatry", "Neuroscience", "Pediatrics"],
  "autism spectrum": ["Psychiatry", "Neuroscience"],
  antidepressant: ["Psychiatry", "Pharmacology"],
  antipsychotic: ["Psychiatry", "Pharmacology"],
  psychotherapy: ["Psychiatry", "Psychology"],
  CBT: ["Psychiatry", "Psychology"],
  "cognitive behavioral": ["Psychiatry", "Psychology"],
  suicide: ["Psychiatry"],
  suicidal: ["Psychiatry"],
  "substance abuse": ["Psychiatry"],
  addiction: ["Psychiatry", "Neuroscience"],
  alcoholism: ["Psychiatry"],
  wellbeing: ["Psychology", "Public Health"],
  "well-being": ["Psychology", "Public Health"],
  therapy: ["Psychiatry", "Psychology"],
  counseling: ["Psychology"],
  counselling: ["Psychology"],
  mindfulness: ["Psychology"],
  resilience: ["Psychology"],
  stress: ["Psychology", "Psychiatry"],
  insomnia: ["Psychiatry", "Neurology"],
  "sleep disorder": ["Psychiatry", "Neurology"],

  // Rheumatology / Autoimmune
  arthritis: ["Rheumatology"],
  "rheumatoid arthritis": ["Rheumatology", "Immunology"],
  lupus: ["Rheumatology", "Immunology"],
  SLE: ["Rheumatology", "Immunology"],
  autoimmune: ["Rheumatology", "Immunology"],
  fibromyalgia: ["Rheumatology"],
  gout: ["Rheumatology"],
  vasculitis: ["Rheumatology", "Immunology"],
  scleroderma: ["Rheumatology", "Immunology"],
  "ankylosing spondylitis": ["Rheumatology"],
  rheumatic: ["Rheumatology"],
  inflammation: ["Rheumatology", "Immunology"],
  inflammatory: ["Rheumatology", "Immunology"],
  "connective tissue": ["Rheumatology"],

  // ============================================================================
  // CLINICAL PROCEDURES & SPECIALTIES
  // ============================================================================

  // Surgery
  surgery: ["Surgery"],
  surgical: ["Surgery"],
  operative: ["Surgery"],
  operation: ["Surgery"],
  incision: ["Surgery"],
  laparoscopic: ["Surgery"],
  laparoscopy: ["Surgery"],
  robotic: ["Surgery"],
  "minimally invasive": ["Surgery"],
  transplant: ["Surgery", "Immunology"],
  transplantation: ["Surgery", "Immunology"],
  graft: ["Surgery", "Immunology"],
  resection: ["Surgery"],
  amputation: ["Surgery"],
  suture: ["Surgery"],
  hernia: ["Surgery"],
  appendectomy: ["Surgery"],
  cholecystectomy: ["Surgery"],
  colectomy: ["Surgery"],
  mastectomy: ["Surgery", "Oncology"],
  gastrectomy: ["Surgery", "Gastroenterology"],
  nephrectomy: ["Surgery", "Urology"],
  thyroidectomy: ["Surgery", "Endocrinology"],
  craniotomy: ["Surgery", "Neurology"],
  "organ transplant": ["Surgery", "Immunology"],
  "liver transplant": ["Surgery", "Gastroenterology"],
  "kidney transplant": ["Surgery", "Nephrology"],
  bariatric: ["Surgery", "Endocrinology"],

  // Anesthesiology
  anesthesia: ["Anesthesiology"],
  anaesthesia: ["Anesthesiology"],
  anesthetic: ["Anesthesiology"],
  anaesthetic: ["Anesthesiology"],
  sedation: ["Anesthesiology"],
  "pain management": ["Anesthesiology"],
  analgesic: ["Anesthesiology", "Pharmacology"],
  analgesia: ["Anesthesiology"],
  "general anesthesia": ["Anesthesiology"],
  "local anesthesia": ["Anesthesiology"],
  "regional anesthesia": ["Anesthesiology"],
  epidural: ["Anesthesiology", "Obstetrics"],
  intubation: ["Anesthesiology", "Critical Care"],
  "pain relief": ["Anesthesiology"],
  "chronic pain": ["Anesthesiology"],
  opioid: ["Anesthesiology", "Pharmacology"],

  // Radiology / Imaging
  imaging: ["Radiology"],
  MRI: ["Radiology"],
  CT: ["Radiology"],
  "CT scan": ["Radiology"],
  "X-ray": ["Radiology"],
  xray: ["Radiology"],
  ultrasound: ["Radiology"],
  sonography: ["Radiology"],
  mammography: ["Radiology", "Oncology"],
  PET: ["Radiology"],
  "PET scan": ["Radiology"],
  fluoroscopy: ["Radiology"],
  angiography: ["Radiology", "Cardiology"],
  "nuclear medicine": ["Radiology"],
  radiograph: ["Radiology"],
  radiologic: ["Radiology"],
  tomography: ["Radiology"],
  contrast: ["Radiology"],
  "magnetic resonance": ["Radiology"],

  // Pathology
  pathology: ["Pathology"],
  pathological: ["Pathology"],
  histology: ["Pathology"],
  histological: ["Pathology"],
  cytology: ["Pathology"],
  cytological: ["Pathology"],
  morphology: ["Pathology"],
  autopsy: ["Pathology"],
  "tissue sample": ["Pathology"],
  specimen: ["Pathology"],
  staining: ["Pathology"],
  immunohistochemistry: ["Pathology"],

  // Critical Care / ICU
  "intensive care": ["Critical Care"],
  ICU: ["Critical Care"],
  "critical care": ["Critical Care"],
  critically: ["Critical Care"],
  mechanical: ["Critical Care"],
  "mechanical ventilation": ["Critical Care"],
  resuscitation: ["Critical Care", "Emergency Medicine"],
  CPR: ["Critical Care", "Emergency Medicine"],
  "organ failure": ["Critical Care"],
  "multi-organ": ["Critical Care"],
  shock: ["Critical Care"],
  ARDS: ["Critical Care", "Pulmonology"],

  // Emergency Medicine
  emergency: ["Emergency Medicine"],
  trauma: ["Emergency Medicine"],
  acute: ["Emergency Medicine"],
  "emergency department": ["Emergency Medicine"],
  ED: ["Emergency Medicine"],
  triage: ["Emergency Medicine"],
  "first aid": ["Emergency Medicine"],
  "acute care": ["Emergency Medicine"],
  poisoning: ["Emergency Medicine"],
  overdose: ["Emergency Medicine"],
  burn: ["Emergency Medicine", "Surgery"],
  burns: ["Emergency Medicine", "Surgery"],
  laceration: ["Emergency Medicine"],
  "cardiac arrest": ["Emergency Medicine", "Cardiology"],

  // ============================================================================
  // RESEARCH & LAB SCIENCE
  // ============================================================================

  // Genetics / Molecular Biology
  DNA: ["Genetics", "Molecular Biology"],
  RNA: ["Genetics", "Molecular Biology"],
  gene: ["Genetics"],
  genes: ["Genetics"],
  genetic: ["Genetics"],
  genomic: ["Genetics"],
  genome: ["Genetics"],
  genomics: ["Genetics"],
  CRISPR: ["Genetics", "Biotechnology"],
  mutation: ["Genetics"],
  polymorphism: ["Genetics"],
  SNP: ["Genetics"],
  allele: ["Genetics"],
  chromosome: ["Genetics"],
  chromosomal: ["Genetics"],
  hereditary: ["Genetics"],
  epigenetic: ["Genetics", "Molecular Biology"],
  epigenetics: ["Genetics", "Molecular Biology"],
  transcription: ["Molecular Biology"],
  translation: ["Molecular Biology"],
  "gene expression": ["Genetics", "Molecular Biology"],
  "gene therapy": ["Genetics", "Biotechnology"],
  genotype: ["Genetics"],
  phenotype: ["Genetics"],
  sequencing: ["Genetics", "Bioinformatics"],
  "whole genome": ["Genetics", "Bioinformatics"],
  exome: ["Genetics"],
  PCR: ["Molecular Biology"],
  "polymerase chain reaction": ["Molecular Biology"],
  "western blot": ["Molecular Biology"],
  electrophoresis: ["Molecular Biology", "Biochemistry"],
  cloning: ["Molecular Biology", "Biotechnology"],
  plasmid: ["Molecular Biology"],
  recombinant: ["Molecular Biology", "Biotechnology"],
  siRNA: ["Molecular Biology"],
  mRNA: ["Molecular Biology", "Genetics"],
  microRNA: ["Molecular Biology", "Genetics"],
  proteomics: ["Molecular Biology", "Biochemistry"],
  transcriptomics: ["Genetics", "Bioinformatics"],
  metabolomics: ["Biochemistry", "Bioinformatics"],

  // Biochemistry
  protein: ["Biochemistry"],
  proteins: ["Biochemistry"],
  enzyme: ["Biochemistry"],
  enzymatic: ["Biochemistry"],
  metabolite: ["Biochemistry"],
  lipid: ["Biochemistry"],
  amino: ["Biochemistry"],
  "amino acid": ["Biochemistry"],
  peptide: ["Biochemistry"],
  kinase: ["Biochemistry"],
  receptor: ["Biochemistry", "Pharmacology"],
  ligand: ["Biochemistry", "Pharmacology"],
  catalysis: ["Biochemistry"],
  oxidative: ["Biochemistry"],
  "oxidative stress": ["Biochemistry"],
  antioxidant: ["Biochemistry"],
  mitochondria: ["Biochemistry", "Cell Biology"],
  mitochondrial: ["Biochemistry", "Cell Biology"],
  ATP: ["Biochemistry"],
  glycolysis: ["Biochemistry"],
  phosphorylation: ["Biochemistry"],

  // Cell Biology / Regenerative Medicine
  cell: ["Cell Biology"],
  cells: ["Cell Biology"],
  cellular: ["Cell Biology"],
  "stem cell": ["Cell Biology", "Regenerative Medicine"],
  "stem cells": ["Cell Biology", "Regenerative Medicine"],
  tissue: ["Cell Biology"],
  "tissue engineering": ["Regenerative Medicine", "Biomedical Engineering"],
  organoid: ["Cell Biology", "Regenerative Medicine"],
  differentiation: ["Cell Biology"],
  proliferation: ["Cell Biology"],
  apoptosis: ["Cell Biology"],
  autophagy: ["Cell Biology"],
  mitosis: ["Cell Biology"],
  meiosis: ["Cell Biology", "Genetics"],
  "cell culture": ["Cell Biology"],
  "in vitro": ["Cell Biology"],
  "in vivo": ["Cell Biology"],
  scaffold: ["Regenerative Medicine", "Biomedical Engineering"],
  regeneration: ["Regenerative Medicine"],
  regenerative: ["Regenerative Medicine"],

  // Microbiology
  microbe: ["Microbiology"],
  microbes: ["Microbiology"],
  microbial: ["Microbiology"],
  bacteria: ["Microbiology"],
  bacterial: ["Microbiology"],
  virus: ["Microbiology"],
  viral: ["Microbiology"],
  virology: ["Microbiology"],
  fungal: ["Microbiology"],
  fungi: ["Microbiology"],
  yeast: ["Microbiology"],
  parasitic: ["Microbiology"],
  parasite: ["Microbiology"],
  microbiome: ["Microbiology"],
  microbiota: ["Microbiology"],
  "gut microbiome": ["Microbiology", "Gastroenterology"],
  probiotic: ["Microbiology"],
  biofilm: ["Microbiology"],
  "culture medium": ["Microbiology"],
  gram: ["Microbiology"],
  "gram-positive": ["Microbiology"],
  "gram-negative": ["Microbiology"],
  bacteremia: ["Microbiology", "Infectious Disease"],

  // Immunology
  immune: ["Immunology"],
  immunity: ["Immunology"],
  immunological: ["Immunology"],
  antibody: ["Immunology"],
  antibodies: ["Immunology"],
  antigen: ["Immunology"],
  vaccine: ["Immunology"],
  vaccination: ["Immunology", "Public Health", "Pediatrics"],
  immunization: ["Immunology", "Public Health"],
  "T-cell": ["Immunology"],
  "T cell": ["Immunology"],
  "B-cell": ["Immunology"],
  "B cell": ["Immunology"],
  cytokine: ["Immunology"],
  interleukin: ["Immunology"],
  interferon: ["Immunology"],
  "immune response": ["Immunology"],
  "immune system": ["Immunology"],
  allergy: ["Immunology"],
  allergic: ["Immunology"],
  anaphylaxis: ["Immunology", "Emergency Medicine"],
  complement: ["Immunology"],
  "monoclonal antibody": ["Immunology", "Biotechnology"],
  "natural killer": ["Immunology"],
  lymphocyte: ["Immunology"],
  macrophage: ["Immunology"],
  neutrophil: ["Immunology", "Hematology"],
  "dendritic cell": ["Immunology"],
  MHC: ["Immunology"],
  HLA: ["Immunology", "Genetics"],
  autoantibody: ["Immunology", "Rheumatology"],
  "checkpoint inhibitor": ["Immunology", "Oncology"],

  // Epidemiology / Public Health
  epidemiology: ["Epidemiology"],
  epidemiological: ["Epidemiology"],
  prevalence: ["Epidemiology"],
  incidence: ["Epidemiology"],
  cohort: ["Epidemiology", "Clinical Research"],
  "case-control": ["Epidemiology", "Clinical Research"],
  outbreak: ["Epidemiology", "Infectious Disease"],
  surveillance: ["Epidemiology", "Public Health"],
  "risk factor": ["Epidemiology"],
  "odds ratio": ["Epidemiology", "Biostatistics"],
  "relative risk": ["Epidemiology", "Biostatistics"],
  mortality: ["Epidemiology"],
  morbidity: ["Epidemiology"],
  "disease burden": ["Epidemiology", "Public Health"],
  "public health": ["Public Health"],
  population: ["Public Health", "Epidemiology"],
  community: ["Public Health"],
  prevention: ["Public Health"],
  screening: ["Public Health"],
  "health policy": ["Public Health"],
  "global health": ["Public Health"],
  "health disparities": ["Public Health"],
  "health equity": ["Public Health"],
  "social determinants": ["Public Health"],
  sanitation: ["Public Health"],
  nutrition: ["Public Health"],
  diet: ["Public Health"],
  "food safety": ["Public Health"],
  tobacco: ["Public Health"],
  smoking: ["Public Health", "Pulmonology"],
  "environmental health": ["Public Health"],
  occupational: ["Public Health"],

  // Clinical Research
  "clinical trial": ["Clinical Research"],
  "clinical trials": ["Clinical Research"],
  RCT: ["Clinical Research"],
  randomized: ["Clinical Research"],
  randomised: ["Clinical Research"],
  placebo: ["Clinical Research"],
  "double-blind": ["Clinical Research"],
  "single-blind": ["Clinical Research"],
  crossover: ["Clinical Research"],
  "phase I": ["Clinical Research"],
  "phase II": ["Clinical Research"],
  "phase III": ["Clinical Research"],
  "phase IV": ["Clinical Research"],
  "informed consent": ["Clinical Research"],
  endpoint: ["Clinical Research"],
  "primary outcome": ["Clinical Research"],
  efficacy: ["Clinical Research"],
  "intention to treat": ["Clinical Research"],
  protocol: ["Clinical Research"],
  "clinical study": ["Clinical Research"],
  "observational study": ["Clinical Research", "Epidemiology"],
  "prospective study": ["Clinical Research", "Epidemiology"],
  "retrospective study": ["Clinical Research", "Epidemiology"],

  // Biostatistics
  statistics: ["Biostatistics"],
  statistical: ["Biostatistics"],
  biostatistics: ["Biostatistics"],
  regression: ["Biostatistics"],
  "meta-analysis": ["Biostatistics"],
  "systematic review": ["Biostatistics", "Clinical Research"],
  "p-value": ["Biostatistics"],
  "confidence interval": ["Biostatistics"],
  "sample size": ["Biostatistics"],
  "power analysis": ["Biostatistics"],
  "survival analysis": ["Biostatistics"],
  "Kaplan-Meier": ["Biostatistics"],
  "Cox regression": ["Biostatistics"],
  "logistic regression": ["Biostatistics"],
  "Bayesian": ["Biostatistics"],
  ANOVA: ["Biostatistics"],
  "chi-square": ["Biostatistics"],
  "hazard ratio": ["Biostatistics"],
  multivariate: ["Biostatistics"],
  "propensity score": ["Biostatistics"],

  // Bioinformatics
  bioinformatics: ["Bioinformatics"],
  computational: ["Bioinformatics"],
  "computational biology": ["Bioinformatics"],
  "machine learning": ["Bioinformatics"],
  "deep learning": ["Bioinformatics"],
  "artificial intelligence": ["Bioinformatics"],
  AI: ["Bioinformatics"],
  "neural network": ["Bioinformatics"],
  algorithm: ["Bioinformatics"],
  pipeline: ["Bioinformatics"],
  "data mining": ["Bioinformatics"],
  "next-generation sequencing": ["Bioinformatics", "Genetics"],
  NGS: ["Bioinformatics", "Genetics"],
  "single-cell": ["Bioinformatics", "Cell Biology"],
  "single cell": ["Bioinformatics", "Cell Biology"],
  "genome-wide": ["Bioinformatics", "Genetics"],
  GWAS: ["Bioinformatics", "Genetics"],
  "systems biology": ["Bioinformatics"],
  network: ["Bioinformatics"],
  "protein structure": ["Bioinformatics", "Biochemistry"],

  // ============================================================================
  // POPULATION & PUBLIC HEALTH
  // ============================================================================

  // Pediatrics
  child: ["Pediatrics"],
  children: ["Pediatrics"],
  pediatric: ["Pediatrics"],
  paediatric: ["Pediatrics"],
  infant: ["Pediatrics"],
  infants: ["Pediatrics"],
  newborn: ["Pediatrics"],
  adolescent: ["Pediatrics"],
  adolescence: ["Pediatrics"],
  childhood: ["Pediatrics"],
  juvenile: ["Pediatrics"],
  "child development": ["Pediatrics"],
  "growth development": ["Pediatrics"],
  breastfeeding: ["Pediatrics", "Obstetrics"],
  congenital: ["Pediatrics", "Genetics"],
  "birth defect": ["Pediatrics", "Genetics"],

  // Sports Medicine
  exercise: ["Sports Medicine"],
  athlete: ["Sports Medicine"],
  athletic: ["Sports Medicine"],
  "sports injury": ["Sports Medicine"],
  "sports medicine": ["Sports Medicine"],
  performance: ["Sports Medicine"],
  "physical activity": ["Sports Medicine", "Public Health"],
  fitness: ["Sports Medicine"],
  rehabilitation: ["Sports Medicine"],
  physiotherapy: ["Sports Medicine"],
  "physical therapy": ["Sports Medicine"],
  doping: ["Sports Medicine"],
  "muscle injury": ["Sports Medicine"],
  sprains: ["Sports Medicine"],
  tendinopathy: ["Sports Medicine", "Orthopedics"],

  // ============================================================================
  // TECHNOLOGY & ENGINEERING
  // ============================================================================

  // Biomedical Engineering
  biomedical: ["Biomedical Engineering"],
  "biomedical engineering": ["Biomedical Engineering"],
  device: ["Biomedical Engineering"],
  "medical device": ["Biomedical Engineering"],
  implant: ["Biomedical Engineering"],
  prosthetic: ["Biomedical Engineering"],
  prosthesis: ["Biomedical Engineering"],
  sensor: ["Biomedical Engineering"],
  biosensor: ["Biomedical Engineering"],
  wearable: ["Biomedical Engineering"],
  "3D printing": ["Biomedical Engineering"],
  biomaterial: ["Biomedical Engineering"],
  nanotechnology: ["Biomedical Engineering", "Pharmacology"],
  nanoparticle: ["Biomedical Engineering", "Pharmacology"],
  microfluidic: ["Biomedical Engineering"],
  telemedicine: ["Biomedical Engineering"],
  telehealth: ["Biomedical Engineering", "Public Health"],
  "point-of-care": ["Biomedical Engineering"],
  "lab-on-chip": ["Biomedical Engineering"],

  // Pharmacology
  drug: ["Pharmacology"],
  drugs: ["Pharmacology"],
  pharmaceutical: ["Pharmacology"],
  pharmacology: ["Pharmacology"],
  pharmacological: ["Pharmacology"],
  dosage: ["Pharmacology"],
  dose: ["Pharmacology"],
  pharmacokinetics: ["Pharmacology"],
  pharmacodynamics: ["Pharmacology"],
  "drug interaction": ["Pharmacology"],
  "drug delivery": ["Pharmacology"],
  formulation: ["Pharmacology"],
  bioavailability: ["Pharmacology"],
  "adverse effect": ["Pharmacology"],
  "side effect": ["Pharmacology"],
  toxicology: ["Pharmacology"],
  toxicity: ["Pharmacology"],
  "drug safety": ["Pharmacology"],
  pharmacogenomics: ["Pharmacology", "Genetics"],
  "drug target": ["Pharmacology"],
  "drug discovery": ["Pharmacology", "Biotechnology"],
  statin: ["Pharmacology", "Cardiology"],
  NSAID: ["Pharmacology"],
  "beta blocker": ["Pharmacology", "Cardiology"],
  "ACE inhibitor": ["Pharmacology", "Cardiology"],
  benzodiazepine: ["Pharmacology", "Psychiatry"],
  "drug metabolism": ["Pharmacology", "Biochemistry"],

  // Biotechnology
  biotechnology: ["Biotechnology"],
  biotech: ["Biotechnology"],
  monoclonal: ["Biotechnology", "Immunology"],
  "gene editing": ["Biotechnology", "Genetics"],
  biopharmaceutical: ["Biotechnology", "Pharmacology"],
  fermentation: ["Biotechnology"],
  bioreactor: ["Biotechnology"],
  "cell therapy": ["Biotechnology", "Regenerative Medicine"],
  CAR: ["Biotechnology", "Oncology", "Immunology"],
  "CAR-T": ["Biotechnology", "Oncology", "Immunology"],

  // Precision Medicine / Translational
  "precision medicine": ["Precision Medicine"],
  personalized: ["Precision Medicine"],
  "personalized medicine": ["Precision Medicine"],
  biomarker: ["Precision Medicine", "Clinical Research"],
  biomarkers: ["Precision Medicine", "Clinical Research"],
  "companion diagnostic": ["Precision Medicine"],
  "translational medicine": ["Translational Medicine"],
  translational: ["Translational Medicine"],
  "bench to bedside": ["Translational Medicine"],
  "targeted therapy": ["Precision Medicine", "Oncology"],

  // ============================================================================
  // GENERAL MEDICAL TERMS
  // ============================================================================

  diagnosis: ["Medicine"],
  diagnostic: ["Medicine"],
  prognosis: ["Medicine"],
  treatment: ["Medicine"],
  etiology: ["Medicine"],
  pathogenesis: ["Medicine"],
  comorbidity: ["Medicine"],
  "internal medicine": ["Medicine"],
  clinical: ["Medicine", "Clinical Research"],
  patient: ["Medicine"],
  patients: ["Medicine"],
  outpatient: ["Medicine"],
  inpatient: ["Medicine"],
  "primary care": ["Medicine"],
  geriatric: ["Medicine"],
  elderly: ["Medicine"],
  aging: ["Medicine"],
  ageing: ["Medicine"],
  palliative: ["Medicine", "Oncology"],
  "end of life": ["Medicine"],
  hospice: ["Medicine"],
  chronic: ["Medicine"],
  "chronic disease": ["Medicine", "Epidemiology"],
  multimorbidity: ["Medicine", "Epidemiology"],
  guideline: ["Medicine", "Clinical Research"],
  "evidence-based": ["Medicine", "Clinical Research"],

  // Physiology
  physiology: ["Physiology"],
  physiological: ["Physiology"],
  homeostasis: ["Physiology"],
  electrolyte: ["Physiology"],
  "acid-base": ["Physiology"],
  hemodynamic: ["Physiology", "Cardiology"],
  thermoregulation: ["Physiology"],
  circadian: ["Physiology", "Neuroscience"],
  "autonomic nervous": ["Physiology", "Neurology"],
  sympathetic: ["Physiology"],
  parasympathetic: ["Physiology"],

  // Sleep Medicine
  sleep: ["Neurology", "Psychiatry"],
  polysomnography: ["Neurology"],
  narcolepsy: ["Neurology"],
  "restless leg": ["Neurology"],
  melatonin: ["Neuroscience", "Endocrinology"],

  // Pain Medicine
  pain: ["Anesthesiology", "Neurology"],
  nociceptive: ["Anesthesiology", "Neuroscience"],
  nociception: ["Neuroscience"],
  "neuropathic pain": ["Neurology", "Anesthesiology"],
  morphine: ["Anesthesiology", "Pharmacology"],
  "nerve block": ["Anesthesiology"],
  CRPS: ["Anesthesiology", "Neurology"],

  // Addiction Medicine
  "substance use": ["Psychiatry", "Public Health"],
  "alcohol use": ["Psychiatry", "Public Health"],
  nicotine: ["Psychiatry", "Public Health"],
  "opioid crisis": ["Public Health", "Psychiatry"],
  naloxone: ["Pharmacology", "Psychiatry"],
  methadone: ["Pharmacology", "Psychiatry"],
  buprenorphine: ["Pharmacology", "Psychiatry"],
  cannabis: ["Psychiatry", "Pharmacology"],
  cocaine: ["Psychiatry"],
  amphetamine: ["Psychiatry", "Pharmacology"],
  withdrawal: ["Psychiatry"],

  // Nutrition
  nutritional: ["Public Health"],
  dietary: ["Public Health", "Endocrinology"],
  vitamin: ["Biochemistry", "Public Health"],
  mineral: ["Biochemistry"],
  "food allergy": ["Immunology", "Gastroenterology"],
  malnutrition: ["Public Health"],
  calorie: ["Endocrinology"],
  "body mass index": ["Endocrinology", "Public Health"],
  BMI: ["Endocrinology", "Public Health"],

  // Dental / Oral
  dental: ["Medicine", "Surgery"],
  tooth: ["Medicine"],
  teeth: ["Medicine"],
  oral: ["Medicine", "Surgery"],
  periodontal: ["Medicine"],
  periodontitis: ["Medicine", "Infectious Disease"],
  caries: ["Medicine"],

  // Rehabilitation
  "occupational therapy": ["Medicine"],
  "speech therapy": ["Neurology"],
  neurorehabilitation: ["Neurology"],
  "gait analysis": ["Sports Medicine", "Biomedical Engineering"],

  // Transplantation
  "organ donation": ["Surgery", "Immunology"],
  "graft rejection": ["Immunology", "Surgery"],
  immunosuppression: ["Immunology", "Pharmacology"],
  immunosuppressive: ["Immunology", "Pharmacology"],
  "heart transplant": ["Surgery", "Cardiology"],
  "lung transplant": ["Surgery", "Pulmonology"],

  // Vascular
  vascular: ["Surgery", "Cardiology"],
  aneurysm: ["Surgery", "Cardiology"],
  "peripheral artery": ["Cardiology", "Surgery"],
  endovascular: ["Surgery", "Radiology"],

  // Plastic Surgery
  "plastic surgery": ["Surgery"],
  reconstruction: ["Surgery"],
  "breast reconstruction": ["Surgery", "Oncology"],
  "skin graft": ["Surgery", "Dermatology"],
  "cleft palate": ["Surgery", "Pediatrics"],
  microsurgery: ["Surgery"],

  // Forensic
  forensic: ["Pathology", "Medicine"],

  // Tropical Medicine
  tropical: ["Infectious Disease", "Public Health"],
  "neglected tropical": ["Infectious Disease", "Public Health"],
  helminth: ["Infectious Disease", "Microbiology"],
  schistosomiasis: ["Infectious Disease"],
  leishmaniasis: ["Infectious Disease"],

  // Toxicology
  toxic: ["Pharmacology"],
  toxin: ["Pharmacology", "Biochemistry"],
  carcinogen: ["Oncology", "Public Health"],
  mutagen: ["Genetics", "Pharmacology"],
  teratogen: ["Obstetrics", "Pharmacology"],
};

// ============================================================================
// Query Expansion Engine
// ============================================================================

/**
 * Expands a user search query using the medical synonym dictionary.
 * Returns deduplicated subject areas that semantically match the query,
 * plus the original query terms.
 *
 * Checks both individual words and multi-word phrases (bigrams, trigrams).
 */
export function expandSearchQuery(query: string): string[] {
  const raw = query.toLowerCase().trim();
  if (!raw) return [];

  const expanded = new Set<string>();

  // 1. Check the full query as-is (handles multi-word entries like "stem cell")
  if (MEDICAL_SYNONYMS[raw]) {
    for (const area of MEDICAL_SYNONYMS[raw]) expanded.add(area.toLowerCase());
  }

  // 2. Generate n-grams (up to trigrams) and check each
  const words = raw.split(/\s+/).filter(Boolean);

  // Trigrams
  for (let i = 0; i <= words.length - 3; i++) {
    const trigram = `${words[i]} ${words[i + 1]} ${words[i + 2]}`;
    if (MEDICAL_SYNONYMS[trigram]) {
      for (const area of MEDICAL_SYNONYMS[trigram]) expanded.add(area.toLowerCase());
    }
  }

  // Bigrams
  for (let i = 0; i <= words.length - 2; i++) {
    const bigram = `${words[i]} ${words[i + 1]}`;
    if (MEDICAL_SYNONYMS[bigram]) {
      for (const area of MEDICAL_SYNONYMS[bigram]) expanded.add(area.toLowerCase());
    }
  }

  // Unigrams
  for (const word of words) {
    if (MEDICAL_SYNONYMS[word]) {
      for (const area of MEDICAL_SYNONYMS[word]) expanded.add(area.toLowerCase());
    }
  }

  // 3. Also add the original query words themselves (for direct name/publisher matching)
  for (const word of words) {
    expanded.add(word);
  }

  return Array.from(expanded);
}
