[build]
builder = "nixpacks"
installCommand = "npm install -g corepack@0.24.1 && corepack enable && pnpm i --no-frozen-lockfile"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
